name: xcube-zenodo
channels:
  - conda-forge
dependencies:
  # Required
  - python >=3.10
  - fsspec
  - numpy
  - requests
  - xarray
  - xcube >=1.8.1
  - zarr >=2.11,<3  # until we can ensure zarr 3 compatibility; see Issue xcube #1102
  # for testing
  - black
  - flake8
  - isort
  - pytest
  - pytest-cov
  - pytest-recording
  - ruff
