name: xcube-zenodo
channels:
  - conda-forge
dependencies:
  # Required
  - python >=3.10
  - fsspec
  - numpy
  - requests
  - tabulate
  - xarray
  - xcube >=1.7.0
  # for testing
  - black
  - flake8
  - pytest
  - pytest-cov
